<#
  ============================================================================
  EZProject - gundsetupdeploy.ps1
  ============================================================================
  Helper script quan ly .env files cho ca Backend va Frontend.
  Tuong thich PowerShell 5.1+ (Windows default).

  Usage:
    .\gundsetupdeploy.ps1 -Mode init            # Khoi tao .env tu .env.example
    .\gundsetupdeploy.ps1 -Mode validate        # Kiem tra .env co du keys chua
    .\gundsetupdeploy.ps1 -Mode show            # Hien thi keys (che gia tri)
    .\gundsetupdeploy.ps1 -Mode export-render   # Xuat keys ra format Render
    .\gundsetupdeploy.ps1 -Mode export-vercel   # Xuat keys ra format Vercel
    .\gundsetupdeploy.ps1 -Mode help            # Hien thi huong dan
  ============================================================================
#>

[CmdletBinding()]
param(
  [ValidateSet('init', 'validate', 'show', 'export-render', 'export-vercel', 'help')]
  [string]$Mode = 'help'
)

$ErrorActionPreference = 'Stop'

# --- Paths ----------------------------------------------------------------
$ScriptRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
$BackendEnv     = Join-Path $ScriptRoot 'Backend\.env'
$BackendExample = Join-Path $ScriptRoot 'Backend\.env.example'
$FrontendEnv     = Join-Path $ScriptRoot 'Frontend\.env'
$FrontendExample = Join-Path $ScriptRoot 'Frontend\.env.example'

# Keys KHONG duoc phep log ra (che gia tri)
$SecretKeys = @(
  'JWT_SECRET', 'JWT_REFRESH_SECRET', 'MONGO_URI',
  'CLOUDINARY_API_KEY', 'CLOUDINARY_API_SECRET',
  'SMTP_PASS', 'ADMIN_PASSWORD'
)

function Write-Banner {
  param([string]$Text)
  Write-Host ''
  Write-Host '========================================' -ForegroundColor Cyan
  Write-Host "  $Text" -ForegroundColor Cyan
  Write-Host '========================================' -ForegroundColor Cyan
  Write-Host ''
}

function Read-EnvFile {
  param([string]$Path)
  if (-not (Test-Path $Path)) { return @{} }
  $map = @{}
  Get-Content $Path | ForEach-Object {
    $line = $_.Trim()
    if ($line -eq '' -or $line.StartsWith('#')) { return }
    $idx = $line.IndexOf('=')
    if ($idx -lt 1) { return }
    $key = $line.Substring(0, $idx).Trim()
    $val = $line.Substring($idx + 1).Trim()
    $map[$key] = $val
  }
  return $map
}

function Write-EnvFile {
  param([string]$Path, [hashtable]$Map)
  $lines = @()
  $lines += '# Auto-generated by gundsetupdeploy.ps1 at ' + (Get-Date -Format 'yyyy-MM-dd HH:mm:ss')
  foreach ($k in ($Map.Keys | Sort-Object)) {
    $lines += "$k=$($Map[$k])"
  }
  Set-Content -Path $Path -Value $lines -Encoding UTF8
}

function Mask-Value {
  param([string]$Key, [string]$Val)
  if ([string]::IsNullOrEmpty($Val)) { return '(empty)' }
  if ($SecretKeys -contains $Key) {
    if ($Val.Length -le 4) { return '****' }
    return $Val.Substring(0, 2) + '****' + $Val.Substring($Val.Length - 2)
  }
  return $Val
}

# -------------------------------------------------------------------------
# MODE: init
# -------------------------------------------------------------------------
function Invoke-Init {
  Write-Banner 'INIT .env FILES FROM .env.example'

  $pairs = @(
    @{ Example = $BackendExample;  Target = $BackendEnv;  Name = 'Backend' },
    @{ Example = $FrontendExample; Target = $FrontendEnv; Name = 'Frontend' }
  )

  foreach ($pair in $pairs) {
    if (-not (Test-Path $pair.Example)) {
      Write-Host "  [SKIP] $($pair.Name): missing $($pair.Example)" -ForegroundColor Yellow
      continue
    }
    if (Test-Path $pair.Target) {
      $ans = Read-Host "  $($pair.Name)\.env da ton tai. Ghi de? (y/N)"
      if ($ans -ne 'y' -and $ans -ne 'Y') {
        Write-Host "  [SKIP] $($pair.Name)" -ForegroundColor Yellow
        continue
      }
    }
    Copy-Item $pair.Example $pair.Target -Force
    Write-Host "  [OK] Created $($pair.Target)" -ForegroundColor Green
  }

  Write-Host ''
  Write-Host 'Buoc tiep theo:' -ForegroundColor Yellow
  Write-Host '  1. Mo Backend\.env, dien MONGO_URI, JWT_SECRET, JWT_REFRESH_SECRET'
  Write-Host '  2. (Optional) Dien CLOUDINARY_* va SMTP_* neu muon dung'
  Write-Host '  3. Mo Frontend\.env, dien VITE_API_URL=http://localhost:3000'
  Write-Host '  4. Chay: cd Backend && npm install && npm run seed'
  Write-Host '  5. Terminal 1: cd Backend && npm run dev'
  Write-Host '  6. Terminal 2: cd Frontend && npm run dev'
}

# -------------------------------------------------------------------------
# MODE: validate
# -------------------------------------------------------------------------
function Invoke-Validate {
  Write-Banner 'VALIDATE .env FILES'

  $required = @{
    'Backend\.env'  = @('NODE_ENV', 'PORT', 'MONGO_URI', 'JWT_SECRET', 'JWT_REFRESH_SECRET', 'CORS_ORIGIN', 'FRONTEND_URL')
    'Frontend\.env' = @('VITE_API_URL')
  }

  $hasError = $false
  foreach ($name in $required.Keys) {
    $path = Join-Path $ScriptRoot $name
    if (-not (Test-Path $path)) {
      Write-Host "  [FAIL] $name - file not found" -ForegroundColor Red
      $hasError = $true
      continue
    }
    $map = Read-EnvFile $path
    $missing = @()
    foreach ($k in $required[$name]) {
      if (-not $map.ContainsKey($k) -or [string]::IsNullOrWhiteSpace($map[$k])) {
        $missing += $k
      }
    }
    if ($missing.Count -gt 0) {
      Write-Host "  [FAIL] $name - missing: $($missing -join ', ')" -ForegroundColor Red
      $hasError = $true
    } else {
      Write-Host "  [OK]   $name - all required keys present" -ForegroundColor Green
    }
  }

  if ($hasError) {
    Write-Host ''
    Write-Host 'Fix: chay .\gundsetupdeploy.ps1 -Mode init de tao lai, hoac xem docs/19_ENVIRONMENT_GUIDE.md' -ForegroundColor Yellow
    exit 1
  }
}

# -------------------------------------------------------------------------
# MODE: show
# -------------------------------------------------------------------------
function Invoke-Show {
  Write-Banner 'SHOW ENV KEYS (values masked)'

  $paths = @($BackendEnv, $FrontendEnv)
  foreach ($path in $paths) {
    if (-not (Test-Path $path)) { continue }
    Write-Host "-- $path --" -ForegroundColor Cyan
    $map = Read-EnvFile $path
    foreach ($k in ($map.Keys | Sort-Object)) {
      $v = Mask-Value $k $map[$k]
      Write-Host ("  {0,-32} = {1}" -f $k, $v)
    }
    Write-Host ''
  }
}

# -------------------------------------------------------------------------
# MODE: export-render
# -------------------------------------------------------------------------
function Invoke-ExportRender {
  Write-Banner 'EXPORT FOR RENDER (copy-paste into Dashboard)'

  if (-not (Test-Path $BackendEnv)) {
    Write-Host '  Backend\.env not found. Run -Mode init first.' -ForegroundColor Red
    exit 1
  }
  $map = Read-EnvFile $BackendEnv
  Write-Host 'Vao Render Dashboard -> Service -> Environment -> Add Environment Variable' -ForegroundColor Yellow
  Write-Host 'Paste tung dong duoi day:' -ForegroundColor Yellow
  Write-Host ''
  foreach ($k in ($map.Keys | Sort-Object)) {
    $v = $map[$k]
    if ([string]::IsNullOrEmpty($v)) {
      Write-Host "  [SKIP] $k - empty, dien tren Dashboard" -ForegroundColor DarkGray
    } else {
      Write-Host "  $k = $v"
    }
  }
}

# -------------------------------------------------------------------------
# MODE: export-vercel
# -------------------------------------------------------------------------
function Invoke-ExportVercel {
  Write-Banner 'EXPORT FOR VERCEL (copy-paste into Project Settings)'

  if (-not (Test-Path $FrontendEnv)) {
    Write-Host '  Frontend\.env not found. Run -Mode init first.' -ForegroundColor Red
    exit 1
  }
  $map = Read-EnvFile $FrontendEnv
  Write-Host 'Vao Vercel -> Project -> Settings -> Environment Variables' -ForegroundColor Yellow
  Write-Host 'Paste tung dong duoi day:' -ForegroundColor Yellow
  Write-Host ''
  foreach ($k in ($map.Keys | Sort-Object)) {
    $v = $map[$k]
    if ([string]::IsNullOrEmpty($v)) {
      Write-Host "  [SKIP] $k - empty, dien tren Vercel" -ForegroundColor DarkGray
    } else {
      Write-Host "  $k = $v"
    }
  }
}

# -------------------------------------------------------------------------
# MODE: help
# -------------------------------------------------------------------------
function Invoke-Help {
  Write-Banner 'EZProject Env Helper - gundsetupdeploy.ps1'
  Write-Host 'Cac lenh:'
  Write-Host ''
  Write-Host '  .\gundsetupdeploy.ps1 -Mode init             ' -NoNewline -ForegroundColor Green
  Write-Host 'Tao .env tu .env.example (neu chua co)'
  Write-Host '  .\gundsetupdeploy.ps1 -Mode validate         ' -NoNewline -ForegroundColor Green
  Write-Host 'Kiem tra .env co du keys chua'
  Write-Host '  .\gundsetupdeploy.ps1 -Mode show             ' -NoNewline -ForegroundColor Green
  Write-Host 'Hien thi keys (che gia tri secret)'
  Write-Host '  .\gundsetupdeploy.ps1 -Mode export-render    ' -NoNewline -ForegroundColor Green
  Write-Host 'Xuat Backend env de paste vao Render Dashboard'
  Write-Host '  .\gundsetupdeploy.ps1 -Mode export-vercel    ' -NoNewline -ForegroundColor Green
  Write-Host 'Xuat Frontend env de paste vao Vercel Project'
  Write-Host '  .\gundsetupdeploy.ps1 -Mode help             ' -NoNewline -ForegroundColor Green
  Write-Host 'Hien thi huong dan nay'
  Write-Host ''
  Write-Host 'Xem chi tiet cach lay tung gia tri tai: docs/19_ENVIRONMENT_GUIDE.md' -ForegroundColor Cyan
}

# --- Dispatch ------------------------------------------------------------
switch ($Mode) {
  'init'           { Invoke-Init }
  'validate'       { Invoke-Validate }
  'show'           { Invoke-Show }
  'export-render'  { Invoke-ExportRender }
  'export-vercel'  { Invoke-ExportVercel }
  default          { Invoke-Help }
}
